spring:
  datasource:
    url: jdbc:mysql://localhost:3306/canaan_assets_management?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    
fileUpload:
  #rootPath: D:/upload/file   #windows
  #rootPath: /usr/local/file               #linux
    
    
